---
title: "GLM"
output: html_document
date: "2023-03-23"
---

```{r}
library(ggplot2)
library(dplyr)
library(readr)
library(tidyverse)
library(broom)
```


```{r}
data_JE_raw <- read_csv("Data_JuliAndEmma.csv")

#have to split for generalization later (correspond WT)

JE_1 <- data_JE_raw %>%
  select(c(1, 2, 3, 6, 7, 8)) %>%
  filter(library != 0, B1_1 != 0 | B2_1 != 0) %>% #remove rows that has library = 0 OR (b1 = 0 AND b2 = 0)
  mutate_all(~ ifelse(. == 0, 0.1, .)) #change value=0 to 0.1

  #GENERALIZE
  #formula: dMut = (Mut B1/ WT B1) / (Mut lib / WT lib)
  JE_1$B1_1dMut <- (JE_1$B1_1/ JE_1$B1_1[1])  / (JE_1$library/ JE_1$library[1])
  JE_1$B2_1dMut <- (JE_1$B2_1/ JE_1$B2_1[1])  / (JE_1$library/ JE_1$library[1])
  JE_1$changeB2_B1 <- JE_1$B2_1dMut - JE_1$B1_1dMut

JE_2 <- data_JE_raw %>%
  select(c(1, 4, 5, 6, 7, 8)) %>%
  filter(library != 0, B1_2 != 0 | B2_2 != 0) %>%
  mutate_all(~ ifelse(. == 0, 0.1, .))

  #GENERALIZE
  #formula: dMut = (Mut B1/ WT B1) / (Mut lib / WT lib)
  JE_2$B1_2dMut <- (JE_2$B1_2/ JE_2$B1_2[1])  / (JE_2$library/ JE_2$library[1])
  JE_2$B2_2dMut <- (JE_2$B2_2/ JE_2$B2_2[1])  / (JE_2$library/ JE_2$library[1])
  JE_2$changeB2_B1 <- JE_2$B2_2dMut - JE_2$B1_2dMut
```

```{r}
#binding
data_JE <- rbind(
  select(JE_1, 'pos', 'mut', 'changeB2_B1'),
  select(JE_2, 'pos', 'mut', 'changeB2_B1')
)
```
# GLM

dMut = (Mut B1/ WT B1) / (Mut lib / WT lib)

```{r}
#set NA of pos = -1 to 0
data_JE[is.na(data_JE)] <- "*"

# Set "2" as the reference level
data_JE$pos <- as.factor(data_JE$pos)
data_JE$pos <- relevel(data_JE$pos, ref = "-1")

# Fit the Gaussian linear regression model
gauss_model <- glm(changeB2_B1 ~ pos * mut, data = data_JE, family = gaussian)
#options(max.print=10000)    #set limit to print the output
# Display the summary of the model
summary(gauss_model)
```

```{r}
fea <- names(coef(gauss_model))[46:length(names(coef(gauss_model)))]      #get features' names

#split the features' names (e.g from "pos137:mutA" to "137" and "A")
mut <- list()
pos <- list ()
for (i in fea){
              str_split <- strsplit(i, ":")
              pos <- append(pos, substr(str_split[[1]][1], 4,6))    # e.g extract 137
              mut <- append(mut, substr(str_split[[1]][2], 4,4))    # e.g extract A
}


est <- coef(gauss_model)[-1][45:length(coef(gauss_model)[-1])]          #get estimated contribution 
#p <- coef(summary(gauss_model))[-1,4]         #get p-value
p <- tidy(gauss_model)$p.value[46:length(tidy(gauss_model)$p.value)]        #to extract all including NA value
```

##### *white box is NA values. *

```{r}
#create data frame of pos, mut, estimated contribution, alpha
data_for_plot<- do.call(rbind, Map(data.frame, Pos=pos, Mut=mut, Est = est, p_value =p))
data_for_plot$alpha <- ifelse(data_for_plot$p_value<0.001,'***', ifelse(0.001 <data_for_plot$p_value & data_for_plot$p_value<0.01,'**', ifelse(0.01<data_for_plot$p_value& data_for_plot$p_value<0.05,'*', ifelse(0.05<data_for_plot$p_value& data_for_plot$p_value<0.1,'.', ' '))))
```

```{r}
# Define the desired order for Pos as a vector
desired_order <- c(1:25)  # Modify this as needed

# Convert Pos to a factor with the desired order
data_for_plot$Pos <- factor(data_for_plot$Pos, levels = desired_order)

#plot estimated contribution vs features
ggplot(data_for_plot, aes(x = Pos, y = Mut)) +
  geom_tile(aes(fill = Est)) + 
  geom_text(aes(label = alpha), size = 3)+
  scale_fill_gradient2(midpoint= 0, na.value = 'white',high = 'darkgoldenrod1 ', low = 'cyan4', mid ='aliceblue')+ 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 75, hjust=1), plot.subtitle = element_text(size = 10, color = "red", face = "bold"))+
  labs(y = "Mutation Amino Acid", x = "Enzyme Position", fill= 'Estimated
Contribution', subtitle = 'Signif. codes:  0 *** 0.001 ** 0.01 * 0.05 . 0.1   1')
```
