---
title: "mimic tissue experiment"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: united
---

```{r}
library(ggplot2)
library(readr)
library(tidyverse)
library(dplyr)
```



## Experiment
```{r, warning=FALSE}
# Read data 
data <- read_csv('https://raw.githubusercontent.com/tranJen/GLMNanoBiT_Honors_Thesis/main/Permeability%20through%20Mimic%20Tissue/ham%20vs%20no%20ham%20RLU.csv')
data
```
## %transmitted for each NanoBiT conjugates
```{r, warning=FALSE}
# Gather the data into a long format and calculate the ratio of Ham = Yes to Ham = No for each sample and each trial
pertrans <- data %>%
  pivot_longer(cols = starts_with("Trial"), names_to = "Trial", values_to = "Value") %>%
  group_by(sample, Trial) %>%
  summarize(Ratio = sum(Value[Ham == "yes"]) / sum(Value[Ham == "no"]), .groups = "drop")


# Create the plot
mimicjit <- ggplot(pertrans, aes(x = sample, y = Ratio*100, color = sample)) +
  geom_jitter(width = 0.1, height = 0, alpha = 1, size = 4) +
  stat_summary(fun.y = "mean", fun.ymin = "mean", fun.ymax= "mean", size=0.3,width=0.5, geom = "crossbar")+
  labs(x = "Sample", y = "% transmitted through tissue") +
  ylim(0,11)+
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 5)) +
  guides(color = FALSE)+
  scale_color_manual(values = c("cornflowerblue","cyan3","darkseagreen","darkgoldenrod1"))+
  theme_classic() +
  theme(text = element_text(size = 15)) +
  coord_fixed(ratio=4/12)
mimicjit
# Save the plot
ggsave("mimic_jitter.png", mimicjit, width = 5, height = 5, units = "in")

```

## RLU

```{r, warning=FALSE}
long <- data %>%pivot_longer(cols = starts_with("Trial"), names_to = "Trial", values_to = "RLU") %>%
  mutate(RLU = ifelse(grepl("Trial", Trial), log10(RLU), RLU))
  

mimic_bar <- ggplot(long, aes(sample,RLU,fill = Ham)) +
  geom_bar(position = 'dodge', stat = 'summary', fun = "mean") +
  geom_errorbar(stat = 'summary', fun.data = "mean_se", position = position_dodge(width = 0.8), width = 0.5) +
  geom_point(aes(x = sample), size = 2, 
             position = position_jitterdodge(jitter.width = 0, jitter.height=0.4, dodge.width=0.89))+
  xlab("Sample") +
  ylab("log[RLU]") +
  labs(fill = "Mimic tissue") +
  scale_fill_manual(values = c("darkslategray3", "azure3")) +
  theme_classic() +
  theme(axis.title = element_text(size = 18), 
        axis.text.x = element_text(size = 12), 
        legend.title = element_text(size = 16))

mimic_bar
# Save the plot
ggsave("mimic_bar.png", mimic_bar, width = 8, height = 6, units = "in")

```

